### ISSUE TITLE
Enable Charge priority color

### ISSUE THREAD

**Issue by paulosergioii** [asterixgaul/digitalbattery13#1]
enable load priority color is not working, nor what color change

ios 13.4.1 (iPhone X)

**Comment by asterixgaul** [comment]
Does not work yet when using apples method

**Comment by paulosergioii** [comment]
is there a forecast of new updates?  thanks for listening

Enviado do meu iPhone

> Em 1 de nov de 2020, à(s) 19:13, asterixgaul <notifications@github.com> escreveu:
> 
> Does not work yet when using apples method

**Comment by asterixgaul** [comment]
Waiting on an a11 jailbreak for iOS 14 to be able to update

**Comment by paulosergioii** [comment]
it seems to me that it already exists, I'm sorry if I'm wrong

Enviado do meu iPhone

> Em 2 de nov de 2020, à(s) 02:23, asterixgaul <notifications@github.com> escreveu:
> 
> Waiting on an a11 jailbreak for iOS 14 to be able to update
